version: "{build}"

clone_depth: 1

environment:
  matrix:
    - nodejs_version: 6
    - nodejs_version: 8
    - nodejs_version: 10

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g grunt-cli
  - npm install

build: off

test_script:
  - grunt jshint jscs nodeunit

cache:
  - node_modules

matrix:
  fast_finish: true
